[options]
admin_passwd = $pbkdf2-sha512$25000$bw1B6P0f49zbW.sdo3RuzQ$9pjRBrtN8jASHD.p850zqKTLyJM6kMFFLyXuiDfJlxo4tul10xdxud16QUXsvRDhHZ4ZtMj8wjvIzcy4VQCQvQ
addons_path = odoo/addons, odoo/test_addons
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = odoo/odoo.log